blank_issues_enabled: false
contact_links:
  - name: Privacy Policy
    url: https://hirohirohotate-sketch.github.io/commitpilot-site/privacy/
    about: イルェットート こたた。
  - name: Quick start
    url: https://hirohirohotate-sketch.github.io/commitpilot-site/
    about: 19月1スイトくっいにちるてすらけー